#!/usr/bin/env python3
"""
Decaying sine tone synthesis
Exponentially decaying sine generated by the two-sample recurrence
    x[n] = 2·rho·cos(ω)·x[n−1] − rho²·x[n−2]
No noise excitation: output is a pure tone from sample zero.
Extent is infinite; crop with CropPE for desired duration.
Parameters: frequency, amplitude, and either duration (seconds to -60 dB)
or rho (per-sample feedback gain).
Copyright (c) 2026 R. Dunbar Poor, Andy Milburn and pygmu2 contributors
MIT License
"""
from pygmu2 import (
    CropPE,
    DecayingSinePE,
    DelayPE,
    MixPE,
    pitch_to_freq,
)
import pygmu2 as pg
from examples_helper import run_demos

pg.set_sample_rate(44100)

SAMPLE_RATE = 44100


def s2s(seconds):
    return int(round(seconds * SAMPLE_RATE))


def _make_note(
    frequency: float = 440.0,
    duration_seconds: float = 1.0,
    amplitude: float = 0.3,
    channels: int = 1,
):
    """Decaying sine cropped to duration_seconds."""
    return CropPE(
        DecayingSinePE(
            frequency=frequency,
            amplitude=amplitude,
            duration=duration_seconds,
            channels=channels,
        ),
        0,
        s2s(duration_seconds),
    )


def demo_single_tone():
    """One 440 Hz tone, 2 s decay to -60 dB."""
    print("=== Decaying sine: single tone (440 Hz, 2 s) ===")
    duration_seconds = 2.0
    tone = _make_note(frequency=440.0, duration_seconds=duration_seconds, amplitude=0.5)
    pg.play(pg.GainPE(CropPE(tone, 0, s2s(duration_seconds)), gain=1.5), SAMPLE_RATE)


def demo_fast_vs_slow_decay():
    """Same pitch: slow decay (2 s) followed by fast decay (0.2 s), with a gap."""
    print("=== Decaying sine: slow decay (2 s) then fast decay (0.2 s) ===")
    notes = []
    t = 0.0

    slow_dur = 2.0
    notes.append(DelayPE(_make_note(frequency=440.0, duration_seconds=slow_dur), s2s(t)))
    t += slow_dur + 0.25

    fast_dur = 0.2
    notes.append(DelayPE(_make_note(frequency=440.0, duration_seconds=fast_dur), s2s(t)))
    t += fast_dur + 0.25

    mix = MixPE(*notes)
    pg.play(pg.GainPE(CropPE(mix, 0, s2s(t)), gain=1.5), SAMPLE_RATE)


def demo_major_triad_chord():
    """C major triad (C4, E4, G4) struck simultaneously — pure sines blend cleanly."""
    print("=== Decaying sine: C major triad (C4, E4, G4) ===")
    midi_notes = [60, 64, 67]
    duration_seconds = 3.0
    voices = [
        _make_note(
            frequency=pitch_to_freq(midi),
            duration_seconds=duration_seconds,
            amplitude=0.1,
        )
        for midi in midi_notes
    ]
    mix = MixPE(*voices)
    pg.play(pg.GainPE(CropPE(mix, 0, s2s(duration_seconds)), gain=1.6), SAMPLE_RATE)


def demo_c_major_arpeggio():
    """C major arpeggio (C4, E4, G4, C5), each note 0.8 s."""
    print("=== Decaying sine: C major arpeggio (C4 E4 G4 C5) ===")
    midi_notes = [60, 64, 67, 72]
    note_dur = 0.8
    notes = []
    t = 0.0
    for midi in midi_notes:
        notes.append(
            DelayPE(
                _make_note(
                    frequency=pitch_to_freq(midi),
                    amplitude=0.2,
                    duration_seconds=note_dur),
                s2s(t),
            )
        )
        t += note_dur
    mix = MixPE(*notes)
    pg.play(pg.GainPE(CropPE(mix, 0, s2s(t)), gain=1.4), SAMPLE_RATE)


def demo_rho_directly():
    """Specify rho directly via rho_for_decay_db for a 1 s, -30 dB partial decay."""
    print("=== Decaying sine: rho specified directly (-30 dB in 1 s) ===")
    duration_seconds = 1.5
    rho = DecayingSinePE.rho_for_decay_db(1.0, SAMPLE_RATE, db=-30.0)
    print(f"  rho = {rho:.6f}")
    tone = CropPE(
        DecayingSinePE(frequency=440.0, amplitude=0.5, rho=rho),
        0,
        s2s(duration_seconds),
    )
    pg.play(pg.GainPE(tone, gain=1.5), SAMPLE_RATE)

def _make_marimba(
    frequency: float = 440.0,
    duration_seconds: float = 1.0,
    amplitude: float = 0.3,
):
    partials = []
    partials.append(
        _make_note(
            frequency=frequency,
            duration_seconds=duration_seconds,
            amplitude = amplitude))
    partials.append(
        _make_note(
            frequency=frequency*4,
            duration_seconds=duration_seconds*0.2,
            amplitude = amplitude*0.5))
    partials.append(
        _make_note(
            frequency=frequency*10,
            duration_seconds=duration_seconds*0.05,
            amplitude = amplitude*0.15))
    mix = MixPE(*partials)
    return mix

def demo_marimba_110():
    duration = 2.0
    marimba = _make_marimba(
        frequency=110,
        duration_seconds=duration,
        amplitude=0.3)
    pg.play(CropPE(marimba, 0, s2s(duration)), SAMPLE_RATE)

def demo_marimba_arpeggio():
    """C diatonic arpeggio (C4, ... C5), each note 0.2 s."""
    print("=== Marimba: C diatonic scale arpeggio (C4 ... C5) ===")
    midi_notes = [
        48, 50, 52, 53, 55, 57, 59,
        60, 62, 64, 65, 67, 69, 71,
        72
        ]
    note_dur = 0.1
    notes = []
    t = 0.0
    for midi in midi_notes:
        notes.append(
            DelayPE(
                _make_marimba(
                    frequency=pitch_to_freq(midi),
                    amplitude=0.2,
                    duration_seconds=note_dur*8),  # overlap
                s2s(t),
            )
        )
        t += note_dur
    mix = MixPE(*notes)
    pg.play(pg.GainPE(CropPE(mix, 0, s2s(t+note_dur*8)), gain=1.4), SAMPLE_RATE)

DEMOS = [
    ("Single tone (440 Hz, 2 s)", demo_single_tone),
    ("Fast vs slow decay (same pitch)", demo_fast_vs_slow_decay),
    ("C major triad (simultaneous)", demo_major_triad_chord),
    ("C major arpeggio", demo_c_major_arpeggio),
    ("Rho specified directly (-30 dB in 1 s)", demo_rho_directly),
    ("Marimba at 110Hz", demo_marimba_110),
    ("Marimba arpeggio", demo_marimba_arpeggio),
]

if __name__ == "__main__":
    run_demos(DEMOS)
